version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - PAYLOAD_SECRET=changeme
      - MONGODB_URI=mongodb://mongo:27017/payload
    depends_on:
      - mongo
